services:
  # Go API backend
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: french_citizenship_api
    restart: unless-stopped
    ports:
      - "8043:8043"
    env_file:
      - .env
    environment:
      # These can override .env values if needed
      - PORT=8043
      - DB_PATH=/app/data/citizenship.db
      - BASE_URL=https://citoyennete.thenightcoders.tech
      - EMAIL_GRACE_PERIOD_HOURS=2
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8043/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  logs: